export const DATA_GET_REQUEST = "DATA_GET_REQUEST";
export const DATA_GET_SUCCESS = "DATA_GET_SUCCESS";
export const DATA_GET_FAILURE = "DATA_GET_FAILURE";

export const DATA_POST_REQUEST = "DATA_POST_REQUEST";
export const DATA_POST_SUCCESS = "DATA_POST_SUCCESS";
export const DATA_POST_FAILURE = "DATA_POST_FAILURE";

export const DATA_EDIT_REQUEST = "DATA_EDIT_REQUEST";
export const DATA_EDIT_SUCCESS = "DATA_EDIT_SUCCESS";
export const DATA_EDIT_FAILURE = "DATA_EDIT_FAILURE";
